### ISSUE TITLE
BCELoss is not safe with fp16

### ISSUE THREAD

**Issue by moyid** [HHousen/TransformerSum#22]
I'm trying to train a longformer model for extractive summarization. It's running out of memory for a V100 GPU, so I tried to use fp16 as allenai suggested. So far, this is the command I'm using:
`python src/main.py --model_name_or_path allenai/longformer-base-4096 --model_type longformer --data_path ./datasets/cnn_dm_extractive_small --weights_save_path ./trained_models --do_train --max_steps 50000 --use_logger tensorboard --no_use_token_type_ids --auto_scale_batch_size binsearch --amp_level 02 --precision 16`

However, I'm getting the following error:
`RuntimeError: torch.nn.functional.binary_cross_entropy and torch.nn.BCELoss are unsafe to autocast.
Many models use a sigmoid layer right before the binary cross entropy layer.
In this case, combine the two layers using torch.nn.functional.binary_cross_entropy_with_logits
or torch.nn.BCEWithLogitsLoss.  binary_cross_entropy_with_logits and BCEWithLogits are
safe to autocast.`

But in your comments in the file `extractive.py` you mentioned that you chose not to use `torch.nn.BCEWithLogitsLoss`, so can you please suggest how to run with fp16?

Thank you.

**Comment by HHousen** [comment]
@moyid I actually became aware of this recently and have a fix already developed. I am currently testing the solution to make sure it does not contain any bugs. If my tests complete successfully then I will be pushing the update in less than 24 hours.

**Comment by HHousen** [comment]
Also, if you do end up training `allenai/longformer-base-4096` for extractive summarization on the full CNN/DM, it'd be greatly appreciated if you open a pull request or issue with the pretrained model so I can add it to the documentation.

**Comment by HHousen** [comment]
Please let me know if 682aaa2 solves this problem.

**Comment by moyid** [comment]
Thank you for making the fix @HHousen ! I just tried it once, and the result is that I'm not getting the BCELoss error anymore, but I still have the CUDA out of memory error.

**Comment by HHousen** [comment]
@moyid I'm not sure about the out of memory error. I would like to try training the model on multiple GPUs, but currently I do not have access to the necessary hardware. If you have multiple GPUs you can try using them with the `--gpus` argument. I'm not sure if there is a memory leak in the code or the problem is that the Longformer simply uses a very large amount of RAM. I think the cause may be the latter.

**Comment by moyid** [comment]
@HHousen if you don't mind me asking, are you able to successfully train a longformer model yet? I can access multiple GPUs, so I'm happy to train one on CNN/DM and contribute, if you can help me debug and get it running.

**Comment by HHousen** [comment]
@moyid Unfortunately, I have been unable to successfully train a longformer model. It's the one thing that I really want to try out with this library. If you can try with multiple GPUs and train on CNN/DM then I'd be glad to help you debug and get it running.
