### ISSUE TITLE
Extractive summarization very short

### ISSUE THREAD

**Issue by michaelroyzen** [HHousen/TransformerSum#28]
This is a very interesting library @HHousen, but my extractive summaries are always two sentences regardless of input document length. How can I increase the length? I would assume that the extractive decoder would, by design, return the top n sentences over a certain threshold?

**Comment by HHousen** [comment]
Whoops! Yes, the number of top sentences to select was hardcoded to 2 in the `ExtractiveSummarizer.predict()` function. Yes, the top `n` sentences are returned. I've updated the library so the `ExtractiveSummarizer.predict()` function has a `num_summary_sentences` argument to specify the number of sentences in the output summary. The default is 3 sentences. Let me know if this works :smile:.
