### ISSUE TITLE
dataloader always can't find data after preparing data for extractive summary

### ISSUE THREAD

**Issue by moyid** [HHousen/TransformerSum#32]
I have noticed this happen consistently -- if the data is not in .pt format and needs to be prepared, if I run the training script (main.py), it will prepare the data, and then fail with dataloader can't find file. But at this point the .pt files are prepared and I just run the same command again and they are found. It is a minor issue but just FYI.

**Comment by HHousen** [comment]
Commit 5737a71 should fix this problem.
