### ISSUE TITLE
Missing key(s) in state_dict

### ISSUE THREAD

**Issue by MorenoLaQuatra** [HHousen/TransformerSum#42]
Good morning, 

First of all thank you for the very interesting project.

I was trying to getting started with the repository using roberta model to perform extractive summarization of simple text, the problem is related to the loading of the model, I report the trace of the error hereafter:

```
Traceback (most recent call last):
  File "/home/moreno/transformersum/transformersum/src/example_extractive.py", line 4, in <module>
    model = ExtractiveSummarizer.load_from_checkpoint("../models/roberta-base-ext-sum")
  File "/home/moreno/anaconda3/envs/transformersum/lib/python3.9/site-packages/pytorch_lightning/core/saving.py", line 158, in load_from_checkpoint
    model = cls._load_model_state(checkpoint, strict=strict, **kwargs)
  File "/home/moreno/anaconda3/envs/transformersum/lib/python3.9/site-packages/pytorch_lightning/core/saving.py", line 204, in _load_model_state
    model.load_state_dict(checkpoint['state_dict'], strict=strict)
  File "/home/moreno/anaconda3/envs/transformersum/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for ExtractiveSummarizer:
        Missing key(s) in state_dict: "word_embedding_model.embeddings.position_ids". 
```

Do you have an idea why it is happening?

**Comment by HHousen** [comment]
@MorenoLaQuatra Did you install the requirements from the `environment.yml` file with `conda env create --file environment.yml`? Running that should have installed `transformers==3.0.2`. If it didn't you can try manually installing version 3.0.2 with `pip install -U transformers==3.0.2`, which should fix the issue.

**Comment by MorenoLaQuatra** [comment]
Yes I did. Actually I get an error while executing `conda env create --file environment.yml`. The environment was created but some libraries were missing (I installed them separately). 

Installing `transformers==3.0.2` solved the issue, do you have any plan to be version-independent?

**Comment by HHousen** [comment]
I do plan to make the project version-independent. In fact, TransformerSum will work with the latest version of `transformers`, it just cannot load models trained with versions <`3.0.2` on versions >`3.0.2`. I'm currently not sure how to accomplish this. I might have to rebuild all of the pre-trained model files. I'm looking into it.

**Comment by HHousen** [comment]
I might be able to load models using the `.from_pretrained()` function from `transformers` and then resave them.

**Comment by HHousen** [comment]
@MorenoLaQuatra I've pushed a change that removes the pinned version. Old models can now be loaded by specifying the `--no_strict` argument.

**Comment by MorenoLaQuatra** [comment]
Thank you for the effort in fixing this.
