### ISSUE TITLE
Import Abstractive is ambiguous

### ISSUE THREAD

**Issue by aliisakroe** [HHousen/TransformerSum#45]
Which module does `from abstractive import AbstractiveSummarizer` refer to? I'd like to follow along with the tutorial, thanks!

**Comment by HHousen** [comment]
It imports the `AbstractiveSummarizer` class from `src/abstractive.py`:
https://github.com/HHousen/TransformerSum/blob/9294897a0ada6b22ace248a47b8d67b2b8d037eb/src/abstractive.py#L83
