### ISSUE TITLE
TransformerSum - Tutorial example is not running?

### ISSUE THREAD

**Issue by alla15747** [HHousen/TransformerSum#50]
**I'm getting this error after running:
 from extractive import ExtractiveSummarizer**

ImportError                               Traceback (most recent call last)
<ipython-input-24-17e82bda8907> in <module>()
----> 1 from extractive import ExtractiveSummarizer
      2 #!python predictions_website.py

11 frames
/usr/local/lib/python3.7/dist-packages/torchtext/vocab.py in <module>()
     11 from typing import Dict, List, Optional, Iterable
     12 from collections import Counter, OrderedDict
---> 13 from torchtext._torchtext import (
     14     Vocab as VocabPybind,
     15 )

ImportError: /usr/local/lib/python3.7/dist-packages/torchtext/_torchtext.so: undefined symbol: _ZN2at6detail10noopDeleteEPv

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.

**Comment by HHousen** [comment]
This doesn't appear to be a problem with TransformerSum and seems like you have an old version of `torchtext` or your environment is somehow corrupted. I'd try manually reinstalling `torchtext` using `pip` and if that didn't work then try to rebuild the environment.
