### ISSUE TITLE
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found

### ISSUE THREAD

**Issue by JoachimJaafar** [HHousen/TransformerSum#52]
Hi,

Here's the command I'm trying to run : 
`python main.py --mode abstractive --model_name_or_path bert-base-uncased --decoder_model_name_or_path bert-base-uncased --cache_file_path data --max_epochs 4 --do_train --do_test --batch_size 4 --weights_save_path model_weights --no_wandb_logger_log_model --accumulate_grad_batches 5 --use_scheduler linear --warmup_steps 8000 --gradient_clip_val 1.0 --custom_checkpoint_every_n 300 --gpus 0`

My env : 
```
name: transformersum
channels:
    - conda-forge
    - pytorch
dependencies:
    - pytorch
    - scikit-learn
    - tensorboard
    - spacy
    - spacy-model-en_core_web_sm
    - sphinx
    - pyarrow=4
    - pip
    - pip:
      - pytorch_lightning
      - transformers
      - torch_optimizer
      - click==7.0
      - wandb
      - rouge-score
      - packaging
      - datasets
      - gdown
      - gradio
      - torch==1.8.1+cu111
      - torchvision==0.9.1+cu111
      - torchaudio==0.8.1
      - -f https://download.pytorch.org/whl/torch_stable.html
variables:
    TOKENIZERS_PARALLELISM: true
```

Here's what I get :
```
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    import datasets as nlp
  File "/opt/conda/envs/transformersum/lib/python3.6/site-packages/datasets/__init__.py", line 23, in <module>
    import pyarrow
  File "/opt/conda/envs/transformersum/lib/python3.6/site-packages/pyarrow/__init__.py", line 63, in <module>
    import pyarrow.lib as _lib
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version GLIBCXX_3.4.26 not found (required by /opt/conda/envs/transformersum/lib/python3.6/site-packages/pyarrow/../../../libarrow.so.400)
```

I'm currently using Python 3.6.13.

Any help is welcome ! :)

**Comment by HHousen** [comment]
This doesn't seem to be an issue with TransformerSum and the issue is being caused by pyarrow. Maybe you could try the steps suggested [in this StackOverflow answer](https://stackoverflow.com/a/55899959). If that doesn't work then try uninstalling pyarrow and [reinstalling](https://arrow.apache.org/docs/python/install.html) with both conda and pip.
