### ISSUE TITLE
predictions_website.py raises AttributeError: '_LazyAutoMapping' object has no attribute '_mapping'

### ISSUE THREAD

**Issue by Laurengcy** [HHousen/TransformerSum#58]
After creating the transformersum conda env, I tried running `python predictions_website.py` and it triggers an error:
```
Traceback (most recent call last):
  File "predictions_website.py", line 8, in <module>
    from extractive import ExtractiveSummarizer  # noqa: E402
  File "/home/msi1/dev_home/transformersum/src/extractive.py", line 39, in <module>
    MODEL_CLASSES = tuple(m.model_type for m in MODEL_MAPPING)  # + CUSTOM_MODEL_CLASSES
  File "/home/msi1/anaconda3/envs/transformersum/lib/python3.7/site-packages/transformers/models/auto/auto_factory.py", line 528, in __iter__
    return iter(self._mapping.keys())
AttributeError: '_LazyAutoMapping' object has no attribute '_mapping'
```

**Comment by Usama3627** [comment]
Experiencing the same issue when trying to `import extractive from ExtractiveSummary`
Initially, the `ModuleNotFoundError: No module named 'extractive'` error was experienced (as mentioned in issue #59 but it was resolved after changing the directory to `src`.

**Comment by Geethi2020** [comment]
Same issue for me as well, with ```import extractive from ExtractiveSummary```. It used to work a couple of weeks ago. Anything changed recently ?
