### ISSUE TITLE
AttributeError: '_LazyAutoMapping' object has no attribute '_mapping'

### ISSUE THREAD

**Issue by BeaBea1234** [HHousen/TransformerSum#60]
For 

    from transformer.models.auto.modeling_auto import MODEL_MAPPING

I get the following error: 

    AttributeError: '_LazyAutoMapping' object has no attribute '_mapping'

The *_LazyAutoMapping* class does indeed not have the attribute *_mapping* (see https://github.com/huggingface/transformers/blob/master/src/transformers/models/auto/auto_factory.py). However, it has a function *def _iter_(self)* that is supposed to *return iter(self._mapping.keys())*, which does not exist in *_init_()*. Am I missing something here or is this an error that needs to be fixed?

This is the error message:

     File "/content/drive/MyDrive/SharedColabNotebooks/Code/transformersum/src/main.py", line 8, in <module>
        from extractive import ExtractiveSummarizer
     File "/content/drive/.shortcut-targets-by- 
        id/1AslFCJkKFwmDS9rtbO_CAdHbBWuL1I4A/SharedColabNotebooks/Code/transformersum/src/extractive.py", line 47, in <module>
         [m.model_type for m in MODEL_MAPPING]
     File "/usr/local/envs/transformersum_test/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 528, in __iter__
           return iter(self._mapping.keys())
    AttributeError: '_LazyAutoMapping' object has no attribute '_mapping'

Any help is greatly appreciated!

**Comment by HHousen** [comment]
This should now be resolved by 1395f378f7b661a1806bc70f653b0e46781dc575. Please let me know if this didn't work.
