### ISSUE TITLE
error when training an extractive summarization model

### ISSUE THREAD

**Issue by CoderBinGe** [HHousen/TransformerSum#63]
I have tried O1, O2, etc… but still reported an error. How to set "amp_level" parameter? When don't support with `amp_backend='apex'`.

![image](https://user-images.githubusercontent.com/26380524/141224243-d127ea32-3a05-4704-ac22-ceddb5a9c464.png)

**Comment by Sere-Fu** [comment]
> 
> 
> I have tried O1, O2, etc… but still reported an error. How to set "amp_level" parameter? When don't support with `amp_backend='apex'`.
> 
> ![image](https://user-images.githubusercontent.com/26380524/141224243-d127ea32-3a05-4704-ac22-ceddb5a9c464.png)

Simply remove the specific arg.

**Comment by CoderBinGe** [comment]
ok, Thanks!
