### ISSUE TITLE
Found keys that are in the model state dict but not in the checkpoint

### ISSUE THREAD

**Issue by PeppaZH** [HHousen/TransformerSum#67]
I'm glad to find such a good project. 
I tried running **_ExtractiveSummarizer.load_from_checkpoint(my_model_path, strict=False_**) and it triggers an error:
UserWarning: Found keys that are in the model state dict but not in the checkpoint: ['word_embedding_model.embeddings.position_ids']
  rank_zero_warn(
I search for the previous issues to solve it , but still the error. Thanks !

**Comment by 1041884221** [comment]
i aslo had such a problem ,have you solved it ?

**Comment by HHousen** [comment]
I believe this is just a warning and can safely be ignored.
