### ISSUE TITLE
A Chinese solution for TransformerSum-extractive, and I've implemented your work in my project

### ISSUE THREAD

**Issue by PolarisRisingWar** [HHousen/TransformerSum#69]
This is part of my repo in which I've imported your project: https://github.com/PolarisRisingWar/text_summarization_chinese/tree/master/models/transformersum/extractive
My project is aiming to provide a general solution on Chinese text data on a bunch of important and famous text summarization model or package, and I've already wriiten codes for extractive part of TransformerSum to act on Chinese text data. If there are problems about citation and other requirements, please tell me.
I've only written Chinese version document, if needed, I can write another English version.

**Comment by HHousen** [comment]
I'm happy to hear that my project has helped you write your own project. Don't worry about citations. As long as you link back to the repo or the documentation (which you already do), then you're good.
